spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: true


